### PR TITLE
Fix issues when cheking object existance

### LINKED ISSUE #29: has() Method Throws Exception Rather than Returning False
Calling `has()` with an invalid file name is resulting in a S3Exception:

    Error executing "HeadObject" on "https://s3.amazonaws.com/[bucket-name]/[file-name]";
    AWS HTTP error: Client error: 403 (client): 403 Forbidden (Request-ID:[hex value])

Sample line of code (taken from a Laravel 5.1 Project)

```php
use Illuminate\Contracts\Filesystem\Cloud;

class S3Controller extends Controller
{
    protected $fs;

    public function __construct(Cloud $fs)
    {
        $this->fs = $fs;
    }
    public function getResource()
    {
        var_dump($this->fs->getDriver()->has('index.html')); // true
        var_dump($this->fs->getDriver()->has('index.htmll')); // Exception; expected false
    }
}
```

### PR DESCRIPTION
**Pull request by svycka**
fixes #29 #38

### CODE REVIEW

**Comment by frankdejonge** [comment]
@svycka could you update the tests for this too?

**Comment by svycka** [comment]
omg :) lets see what can I do.

**Comment by svycka** [comment]
@frankdejonge is it ok?

File: spec/AwsS3AdapterSpec.php [hunk 1]
```diff
@@ -521,6 +520,14 @@ public function getMatchers()
     /**
      * @param $key
      */
+    private function make_it_404_on_has_object($key)
+    {
+        $this->client->doesObjectExist($this->bucket, $key)->willReturn(false);
+    }
+
+    /**
+     * @param $key
```
Comment (GrahamCampbell) [inline spec/AwsS3AdapterSpec.php]: this phpdoc is meaningless unless you specify a type, otherwise, I think you should just remove the phpdoc because it adds nothing

Comment (GrahamCampbell) [inline spec/AwsS3AdapterSpec.php]: infact, it's actually invalid without a type specified

Comment (svycka) [inline spec/AwsS3AdapterSpec.php]: agree, but then would be good idea to remove all params like this or add string type

Comment (svycka) [inline spec/AwsS3AdapterSpec.php]: This could be done in new PR.

**Comment by svycka** [comment]
@frankdejonge do you plan merging this? as this is big issue for me because current behavior is against interface description [interface description](https://github.com/thephpleague/flysystem/blob/5fbe9274353712d42b343615a0d1daa9d2e4576f/src/FilesystemInterface.php#L7-L14) as description says it should return boolean but instead it throws exception so I would have to create workaround for S3 adapter

**Comment by frankdejonge** [comment]
@svycka I'll check this out this evening. Side-note: the interface you're hinting at it the FilesystemInterface, while this adapter implements an AdapterInterface which is not the same. The method implements the has method from the ReadInterface which the AdapterInterface is an extension of and fulfils it's requirement: https://github.com/thephpleague/flysystem/blob/5fbe9274353712d42b343615a0d1daa9d2e4576f/src/ReadInterface.php#L14
